### ISSUE TITLE
unable to publish without specific partitionId

### ISSUE THREAD

**Issue by er999mi** [Spinoco/fs2-kafka#5]
for example, in "publishN" function, i must mention a specific partition id.

is there a way to get around it ?

  def publishN(
    topicId: String @@ TopicName
    , partition: Int @@ PartitionId
    , requireQuorum: Boolean
    , serverAckTimeout: FiniteDuration
    , compress: Option[Compression.Value]
  )(messages: Chunk[(ByteVector, ByteVector)]): F[Long]

**Comment by pchlupacek** [comment]
I am afraid that, partitionId is requirement of kafka. When you publish to kafka you must provide topic name and partition number.

**Comment by er999mi** [comment]
@pchlupacek thanks for your reply.

According to the api doc of **ProducerRecord**, we can create various records with/without partition, as also with/without key and publish(send) them.

https://kafka.apache.org/0110/javadoc/org/apache/kafka/clients/producer/ProducerRecord.html

https://kafka.apache.org/0110/javadoc/index.html?org/apache/kafka/clients/producer/KafkaProducer.html

**Comment by er999mi** [comment]
btw, same issue in the consumer part. 
we must specify the partitionId in the api.

**Comment by pchlupacek** [comment]
@er999mi I see what you mean. Apis states

> If a valid partition number is specified that partition will be used when sending the record. If no partition is specified but a key is present a partition will be chosen using a hash of the key. If neither key nor partition is present a partition will be assigned in a round-robin fashion.

Note that this is not functionality of simple subscriber, that simply requires partition. You can however very easily implement both in your user code, by first querying the partitions and then perform whatever function to generate partition for your message.

**Comment by er999mi** [comment]
@er999mi can't it be implemented with the native api on the library side ?

**Comment by pchlupacek** [comment]
@er999mi One of the design choices we made here was to not depend on original kafka driver. There are areas, where we don't like concurrency model of native kafka driver, and for that reason we essentially reimplemented the driver to be fully asynchronous and non blocking, solely in fs2. So there is no current plan to add kafka dependency. 

Having said that you may do this in your project, and use whatever helpers you may need from the kafka native driver.
