### ISSUE TITLE
Cannot specify "group.id" when trying to subscribe, in order to consume messages.

### ISSUE THREAD

**Issue by er999mi** [Spinoco/fs2-kafka#7]

**Comment by pchlupacek** [comment]
@er999mi this is not implemented. GroupId is not functionality of the simple consumer.

**Comment by er999mi** [comment]
@@er999mi  will it ever implemented ?

**Comment by pchlupacek** [comment]
@er999mi there is no such current plan to support anything above Simple Consumer. We strongly believe that business logic and distribution amongst the partitions is responsibility of user code. We may review this in future, if there will be more requests for this feature, and/or when there will be volunteer to implement that.
