### ISSUE TITLE
fs2 0.10 support

### ISSUE THREAD

**Issue by coltfred** [Spinoco/fs2-kafka#8]
Now that Cats 1.0.0-RC1 is out and fs2 0.10 is near final, it'd be nice to get a version built on top of those versions.

**Comment by pchlupacek** [comment]
@coltfred yeah. We may perhaps get out RC-1 with 0.10 support as we did for fs2-http ...

**Comment by coltfred** [comment]
@pchlupacek Is this likely to be difficult? We're going to start working with some Kafka later this week in an http4s 0.18/fs2 0.10 application. My current knowledge of FS2 is weak at best so I doubt I can tackle the upgrade solo, but I also understand it might not be a priority for you.

**Comment by pchlupacek** [comment]
@coltfred not, it shouldn't be a big deal. If you want to tackle it I can give you support with that (gitter etc) or I may find some time for ti over weekend.

**Comment by pchlupacek** [comment]
the preview 0.10 version of fs2-kafka is available as series/0.2.0 branch. Note is not yet finaliazed and some tests are still failing.

**Comment by felixmulder** [comment]
any update on this? :)

**Comment by coltfred** [comment]
I haven't had time to poke at it at all. I think I saw @AdamChlupacek in the gitter talking about working on it, but I could be misunderstanding.

**Comment by pchlupacek** [comment]
just to clarify status of it. We are waiting for stable/RC fs2 0.10 release before publishing this. This shall be hopefully mater of days

**Comment by AdamChlupacek** [comment]
The 0.2.0 version (fs2 0.10.x) is already out. Closing this.
